@WorkflowApp.Api_HostAddress=http://localhost:5071
@token=YOUR_JWT_TOKEN_HERE

### register
POST {{WorkflowApp.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "loginId": "testuser",
  "displayName": "Test User",
  "password": "Password123"
}

### login
POST {{WorkflowApp.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "loginId": "testuser",
  "password": "Password123"
}

##### 動作しなかったためコメントアウト
GET {{WorkflowApp.Api_HostAddress}}/api/sample/me
Authorization: Bearer {{token}}

###
POST {{WorkflowApp.Api_HostAddress}}/api/applications
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "出張申請",
  "content": "4月10日の東京出張について申請します。"
}

### update status
@id=7
PATCH {{WorkflowApp.Api_HostAddress}}/api/applications/{{id}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "Approved"
}

### get applications
GET {{WorkflowApp.Api_HostAddress}}/api/applications?page=1&pageSize=10
Authorization: Bearer {{token}}


### get approvers
GET {{WorkflowApp.Api_HostAddress}}/api/users/approvers
Authorization: Bearer {{token}}